module.exports.filter = require('./filter')
module.exports.map = require('./map')
module.exports.forEach = require('./forEach')
module.exports.mapObject = require('./mapObject')
module.exports.reduce = require('./reduce')
